---
title: "PCA_final"
author: "Diana Lin"
date: "29/03/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.align = 'center')
```

```{r load libraries, include = FALSE}
library(tidyverse)
library(here)
library(glue)
library(gridExtra)
library(knitr)
library(scales)
library(cowplot)
library(gridExtra)
library(lumi)
```

Load the scaled beta-values:

```{r load data}
if (!exists("metadata", inherits = FALSE) ) {
    metadata <- readRDS(file = here("data", "processed_data", "metadata.rds"))
}

if (!exists("expr_scaled", inherits = FALSE) ) {
    expr <- readRDS(file = here("data", "raw_data", "data.rds")) %>%
      column_to_rownames(var = "CG")
    expr_scaled <- t(scale(t(expr)))
}
```

```{r pca}
pcs <- prcomp(na.omit(expr_scaled), center = FALSE, scale = FALSE)

plot(pcs)

prinComp <-
    cbind(metadata, pcs$rotation[metadata$sample, 1:10]) %>% 
    dplyr::select(-sample)
    
plot(prinComp[, c("cancer", "cancer_type", "PC1", "PC2", "PC3")], pch = 19, cex = 0.8)
```

```{r summary}
kable(summary(pcs)$importance[,1:10])
```

```{r plots}
pca <- function(pc1 = "PC1", pc2 = "PC2", var = "cancer_type") {
    ggplot(prinComp, aes(x = !!sym(pc1), y = !!sym(pc2))) +
        geom_point(aes(colour = !!sym(var))) +
        labs(title = var,
             subtitle = glue("{pc1} and {pc2}")) +
    #    scale_colour_discrete(labels = function(x) str_wrap(x, width = 13)) +
     #   guides(colour = guide_legend(nrow = 2)) +
        theme_cowplot(12) +
        xlim(c(-0.4,0.4))
}
p1 <- pca(pc1 = "PC1", pc2 = "PC2", var = "cancer_type") 
p2 <- pca(pc1 = "PC1", pc2 = "PC3", var = "cancer_type")
p3 <- pca(pc1 = "PC2", pc2 = "PC3", var = "cancer_type") 

p4 <- pca(pc1 = "PC1", pc2 = "PC2", var = "cancer") 
p5 <- pca(pc1 = "PC1", pc2 = "PC3", var = "cancer")
p6 <- pca(pc1 = "PC2", pc2 = "PC3", var = "cancer") 

p7 <- plot_grid(
    p1 + theme(legend.position = 'none'),
    p2 + theme(legend.position = 'none'),
    p3 + theme(legend.position = 'none'),
    labels =  c('A', 'B', 'C'),
    align = 'h',
    nrow = 1)

p8 <- plot_grid(
    p4 + theme(legend.position = 'none'),
    p5 + theme(legend.position = 'none'),
    p6 + theme(legend.position = 'none'),
    labels = c('D', 'E', 'F'),
    align = 'h',
    nrow = 1
)
legend1 <- get_legend(
  p1 + theme(legend.box.margin = margin(0, 0, 0, 12),
             legend.title = element_blank()) 
)

legend2 <- get_legend(
  p4 + theme(legend.box.margin = margin(0, 0, 0, 12),
      legend.title = element_blank()) + 
      scale_colour_discrete(labels = function(x) str_wrap(x, width = 20))# + 
  #    guides(colour = guide_legend(nrow = 2))
)

p9 <- plot_grid(p7, legend1, rel_widths = c(3, 1.5))
p10 <- plot_grid(p8, legend2, rel_widths = c(3, 1.5))

title <- ggdraw() + 
  draw_label(
    "PCA of Differential Methylation M-values",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 7)
  )

final <- plot_grid(title, p9, p10, ncol = 1, rel_heights = c(0.1, 1,1))

print(final)
```



